{"uuid": "a28be113-a356-434f-bf71-ed4798043dd3", "counter": 46, "stdout": "fatal: [server1]: FAILED! => {\"msg\": \"The conditional check 'vpn_username in hostvars[inventory_hostname] or vpn_username != default('vpn_username')' failed. The error was: error while evaluating conditional (vpn_username in hostvars[inventory_hostname] or vpn_username != default('vpn_username')): 'default' is undefined\\n\\nThe error appears to be in '/home/bakvivas/Documents/Projects/ansible-role-3x-ui/roles/3x_ui_container/tasks/start_container.yml': line 14, column 3, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n\\n- name: Debug vpn_username\\n  ^ here\\n\"}", "start_line": 50, "end_line": 51, "runner_ident": "624df1ce-448c-4b93-bd22-a233b2535074", "event": "runner_on_failed", "pid": 9478, "created": "2024-12-03T22:34:17.397651+00:00", "parent_uuid": "985f4199-2370-b8ad-484c-00000000005b", "event_data": {"playbook": "playbook.yml", "playbook_uuid": "524fcd78-1f1d-47a3-8522-46938b3d8902", "play": "start docker", "play_uuid": "985f4199-2370-b8ad-484c-000000000002", "play_pattern": "3x_ui_server", "task": "Debug vpn_username", "task_uuid": "985f4199-2370-b8ad-484c-00000000005b", "task_action": "fail", "resolved_action": "ansible.builtin.fail", "task_args": "", "task_path": "/home/bakvivas/Documents/Projects/ansible-role-3x-ui/roles/3x_ui_container/tasks/start_container.yml:14", "role": "3x_ui_container", "host": "server1", "remote_addr": "server1", "res": {"msg": "The conditional check 'vpn_username in hostvars[inventory_hostname] or vpn_username != default('vpn_username')' failed. The error was: error while evaluating conditional (vpn_username in hostvars[inventory_hostname] or vpn_username != default('vpn_username')): 'default' is undefined\n\nThe error appears to be in '/home/bakvivas/Documents/Projects/ansible-role-3x-ui/roles/3x_ui_container/tasks/start_container.yml': line 14, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Debug vpn_username\n  ^ here\n", "_ansible_no_log": false}, "start": "2024-12-03T22:34:17.387080+00:00", "end": "2024-12-03T22:34:17.397562+00:00", "duration": 0.010482, "ignore_errors": null, "event_loop": null, "uuid": "a28be113-a356-434f-bf71-ed4798043dd3"}}